from typing import Any, Callable

from kivy.clock import ClockBase

class Clock(ClockBase):
    def __init__(self) -> None: ...
    @classmethod
    def schedule_once(
        cls, func: Callable[[Callable[Any, ...], float], int], timeout: float
    ) -> int: ...
    @classmethod
    def schedule_interval(
        cls, func: Callable[[float], None], timeout: float
    ) -> int: ...
    def unschedule(self, func: Callable) -> None: ...
    def unschedule_once(self, func: Callable) -> None: ...
    def get_time(self) -> float: ...
    def get_time_msec(self) -> int: ...
    def get_time_sec(self) -> float: ...
    def get_time_usec(self) -> int: ...
    def get_time_nsec(self) -> int: ...
