"""
This type stub file was generated by pyright.
"""

from kivy.core.image import ImageLoaderBase
from kivy.utils import deprecated

'''
Pygame: Pygame image loader

.. warning::

    Pygame has been deprecated and will be removed in the release after Kivy
    1.11.0.
'''
__all__ = ('ImageLoaderPygame', )
class ImageLoaderPygame(ImageLoaderBase):
    '''Image loader based on the PIL library'''
    @deprecated(msg='Pygame has been deprecated and will be removed after 1.11.0')
    def __init__(self, *largs, **kwargs) -> None:
        ...
    
    @staticmethod
    def extensions(): # -> tuple[Literal['bmp']] | tuple[Literal['jpg'], Literal['jpeg'], Literal['jpe'], Literal['png'], Literal['bmp'], Literal['pcx'], Literal['tga'], Literal['tiff'], Literal['tif'], Literal['lbm'], Literal['pbm'], Literal['ppm'], Literal['xpm']]:
        '''Return accepted extensions for this loader'''
        ...
    
    @staticmethod
    def can_save(fmt, is_bytesio): # -> bool:
        ...
    
    @staticmethod
    def can_load_memory(): # -> Literal[True]:
        ...
    
    def load(self, filename):
        ...
    
    @staticmethod
    def save(filename, width, height, pixelfmt, pixels, flipped, imagefmt=...): # -> Literal[True]:
        ...
    


