"""
This type stub file was generated by pyright.
"""

from kivy.core.image import ImageLoaderBase

'''
DDS: DDS image loader
'''
__all__ = ('ImageLoaderDDS', )
class ImageLoaderDDS(ImageLoaderBase):
    @staticmethod
    def extensions(): # -> tuple[Literal['dds']]:
        ...
    
    def load(self, filename): # -> list[ImageData]:
        ...
    


