"""
This type stub file was generated by pyright.
"""

from kivy.core.image import ImageLoaderBase

'''
PIL: PIL image loader
'''
__all__ = ('ImageLoaderPIL', )
class ImageLoaderPIL(ImageLoaderBase):
    '''Image loader based on the PIL library.

    .. versionadded:: 1.0.8

    Support for GIF animation added.

    Gif animation has a lot of issues(transparency/color depths... etc).
    In order to keep it simple, what is implemented here is what is
    natively supported by the PIL library.

    As a general rule, try to use gifs that have no transparency.
    Gif's with transparency will work but be prepared for some
    artifacts until transparency support is improved.

    '''
    @staticmethod
    def can_save(fmt, is_bytesio): # -> bool:
        ...
    
    @staticmethod
    def can_load_memory(): # -> Literal[True]:
        ...
    
    @staticmethod
    def extensions(): # -> tuple[Any | str, ...]:
        '''Return accepted extensions for this loader'''
        ...
    
    def load(self, filename): # -> list[ImageData]:
        ...
    
    @staticmethod
    def save(filename, width, height, pixelfmt, pixels, flipped=..., imagefmt=...): # -> Literal[True]:
        ...
    


