"""
This type stub file was generated by pyright.
"""

from kivy.core.image import ImageLoaderBase

'''
SDL2 image loader
=================
'''
__all__ = ('ImageLoaderSDL2', )
class ImageLoaderSDL2(ImageLoaderBase):
    '''Image loader based on SDL2_image'''
    @staticmethod
    def extensions(): # -> tuple[Literal['bmp'], Literal['jpg'], Literal['jpeg'], Literal['jpe'], Literal['lbm'], Literal['pcx'], Literal['png'], Literal['pnm'], Literal['tga'], Literal['tiff'], Literal['webp'], Literal['xcf'], Literal['xpm'], Literal['xv']]:
        '''Return accepted extensions for this loader'''
        ...
    
    @staticmethod
    def can_save(fmt, is_bytesio): # -> bool:
        ...
    
    @staticmethod
    def can_load_memory(): # -> Literal[True]:
        ...
    
    def load(self, filename): # -> list[ImageData]:
        ...
    
    @staticmethod
    def save(filename, width, height, pixelfmt, pixels, flipped, imagefmt): # -> Literal[True]:
        ...
    


