"""
This type stub file was generated by pyright.
"""

from ffpyplayer.tools import get_log_callback
from kivy.core.image import ImageLoaderBase

'''
FFPyPlayer: FFmpeg based image loader
'''
__all__ = ('ImageLoaderFFPy', )
logger_func = ...
if not get_log_callback():
    ...
class ImageLoaderFFPy(ImageLoaderBase):
    '''Image loader based on the ffpyplayer library.

    .. versionadded:: 1.9.0

    .. note:
        This provider may support more formats than what is listed in
        :meth:`extensions`.
    '''
    @staticmethod
    def extensions(): # -> tuple[Literal['bmp'], Literal['dpx'], Literal['exr'], Literal['gif'], Literal['ico'], Literal['jpeg'], Literal['jpg2000'], Literal['jpg'], Literal['jls'], Literal['pam'], Literal['pbm'], Literal['pcx'], Literal['pgm'], Literal['pgmyuv'], Literal['pic'], Literal['png'], Literal['ppm'], Literal['ptx'], Literal['sgi'], Literal['ras'], Literal['tga'], Literal['tiff'], Literal['webp'], Literal['xbm'], Literal['xface'], Literal['xwd']]:
        '''Return accepted extensions for this loader'''
        ...
    
    def load(self, filename): # -> list[ImageData]:
        ...
    


