"""
This type stub file was generated by pyright.
"""

from kivy.core.image import ImageLoaderBase

'''
Tex: Compressed texture
'''
__all__ = ('ImageLoaderTex', )
class ImageLoaderTex(ImageLoaderBase):
    @staticmethod
    def extensions(): # -> tuple[Literal['tex']]:
        ...
    
    def load(self, filename): # -> list[ImageData]:
        ...
    


