from typing import Tuple

from kivy.graphics import Canvas
from kivy.uix.widget import Widget

class Layout(Widget):
    children: Tuple[Widget, ...]
    canvas: Canvas

    def add_widget(self, widget: Widget, *args, **kwargs) -> None: ...
    def remove_widget(self, widget: Widget, *args, **kwargs) -> None: ...
    def bind(self, **kwargs) -> None: ...
    def fbind(self, **kwargs) -> None: ...
    def do_layout(self, *largs) -> None: ...
