"""
This type stub file was generated by pyright.
"""

from kivy.uix.widget import Widget

'''
Progress Bar
============

.. versionadded:: 1.0.8

.. image:: images/progressbar.jpg
    :align: right

The :class:`ProgressBar` widget is used to visualize the progress of some task.
Only the horizontal mode is currently supported: the vertical mode is not
yet available.

The progress bar has no interactive elements and is a display-only widget.

To use it, simply assign a value to indicate the current progress::

    from kivy.uix.progressbar import ProgressBar
    pb = ProgressBar(max=1000)

    # this will update the graphics automatically (75% done)
    pb.value = 750

'''
__all__ = ('ProgressBar', )
class ProgressBar(Widget):
    '''Class for creating a progress bar widget.

    See module documentation for more details.
    '''
    def __init__(self, **kwargs) -> None:
        ...
    
    value = ...
    def get_norm_value(self): # -> float | Literal[0]:
        ...
    
    def set_norm_value(self, value): # -> None:
        ...
    
    value_normalized = ...
    max = ...


if __name__ == '__main__':
    ...
