from typing import Any
from kivy.app import Widget

class TabbedPanelItem:
    def add_widget(self, widget: Widget, *args: Any, **kwargs: Any) -> None: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TabbedPanel:
    def add_widget(
        self, widget: TabbedPanelItem, *args: Any, **kwargs: Any
    ) -> None: ...
    def remove_widget(
        self, widget: TabbedPanelItem, *args: Any, **kwargs: Any
    ) -> None: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
